### ISSUE TITLE
PHP v7 Update?

### ISSUE THREAD

**Issue by jlev** [suprsidr/WPG2#1]
I know this code and repository is incredibly old, but I've been updating a legacy site with it from PHP5 to 7. In addition to using [a fork of Gallery2](https://github.com/gregstoll/gallery2), you may also need to fix two lines in wpg2embed.inc to resolve [this issue](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php#reference.pcre.pattern.modifiers.eval). 

Drop the `e` from these regexes, and it will continue to work.
1229: `$output = preg_replace("/<wpg2>(.*?)<\/wpg2>/ei", "g2_tagimageblock('\\1')", $text);`
1245: `$output = preg_replace("/<wpg2id>(.*?)<\/wpg2id>/ei", "g2_tagimageblock('\\1')", $text);`

**Comment by suprsidr** [comment]
Thanks, fixed.
Do you know what PHP versions are supported in that gallery fork?
gallery started breaking around PHP 5.7

**Comment by jlev** [comment]
My change before was incorrect, and just caused the "g2_tagimageblock" to be rendered out as text instead of actually evaluated and replaced.

I've fixed that in my fork by using `preg_replace_callback` instead like https://github.com/jlev/WPG2/blob/master/wpg2embed.inc#L1229. Also fixed a few other things that are causing PHP notices.

Unfortunately it's still not working in version 7, with just missing output and no errors or debug logs. I'm at a loss for how to proceed further, and may just end up staying on version 5.6 for the time being.
